vpc-name      = "Jenkins-vpc"
igw-name      = "Jenkins-igw"
subnet-name   = "Jenkins-subnet"
rt-name       = "Jenkins-route-table"
sg-name       = "Jenkins-sg"
instance-name = "Jenkins-server-jirayu"
key-name      = "Jirayu-Key-pair"
iam-role      = "Jenkins-iam-role-jirayu"
